In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("Data Cleaning 12.08.csv")
df.head()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.743,0.289,1.011,6.3830,0.078,0.078,1.152,NaN
1,112 Psc b,Confirmed,NaN,0.005,0.004,0.0330,0.005,0.004,NaN,NaN
2,112 Psc c,Confirmed,9.866,1.781,3.190,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,NaN,1.100,1.100,11.0873,1.100,1.100,NaN,NaN
4,14 And Ab,Confirmed,NaN,0.230,0.230,4.6840,0.230,0.230,NaN,NaN

In [2]:
df.duplicated().sum()

np.int64(0)

In [3]:
df.shape

(5986, 10)

In [4]:
df.isnull().sum()

name                      0
planet_status             0
mass                   3907
mass_error_min         3169
mass_error_max         3169
mass_sini              4784
mass_sini_error_min    4947
mass_sini_error_max    4947
radius                 1418
radius_error_min       1893
dtype: int64

In [5]:
# Fix missing mass by combining mass and mass_sini
df['mass'] = df['mass'].fillna(df['mass_sini'])

In [6]:
df.head()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.7430,0.289,1.011,6.3830,0.078,0.078,1.152,NaN
1,112 Psc b,Confirmed,0.0330,0.005,0.004,0.0330,0.005,0.004,NaN,NaN
2,112 Psc c,Confirmed,9.8660,1.781,3.190,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,11.0873,1.100,1.100,11.0873,1.100,1.100,NaN,NaN
4,14 And Ab,Confirmed,4.6840,0.230,0.230,4.6840,0.230,0.230,NaN,NaN

In [7]:
df.isnull().sum()

name                      0
planet_status             0
mass                   2924
mass_error_min         3169
mass_error_max         3169
mass_sini              4784
mass_sini_error_min    4947
mass_sini_error_max    4947
radius                 1418
radius_error_min       1893
dtype: int64

In [8]:
# drop rows that are still missing in mass column
df = df.dropna(subset=['mass'])

In [9]:
df.isnull().sum()

name                      0
planet_status             0
mass                      0
mass_error_min          245
mass_error_max          245
mass_sini              1860
mass_sini_error_min    2023
mass_sini_error_max    2023
radius                 1418
radius_error_min       1500
dtype: int64

In [10]:
# Fix missing errors by fixing the empty values with 0 so that the calculations won't break
error_cols = ['mass_error_min', 'mass_error_max', 'mass_sini_error_min', 'mass_sini_error_max', 'radius_error_min']
for col in error_cols:
    df[col] = df[col].fillna(0)

In [11]:
df.isnull().sum()

name                      0
planet_status             0
mass                      0
mass_error_min            0
mass_error_max            0
mass_sini              1860
mass_sini_error_min       0
mass_sini_error_max       0
radius                 1418
radius_error_min          0
dtype: int64

In [12]:
# Fix missing radius
df['radius'] = df['radius'].fillna(df['radius'].median())

In [13]:
df.isnull().sum()

name                      0
planet_status             0
mass                      0
mass_error_min            0
mass_error_max            0
mass_sini              1860
mass_sini_error_min       0
mass_sini_error_max       0
radius                    0
radius_error_min          0
dtype: int64

In [14]:
# drop the redundant mass_sini column
df = df.drop(columns=['mass_sini'])

In [15]:
df.to_csv("Cleaned_Exoplanet_Data_Final.csv", index=False)

In [16]:
df.describe()

,mass,mass_error_min,mass_error_max,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
count,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000
mean,1.653834,0.298412,inf,0.072848,0.081591,0.699602,0.037602
std,2.866224,1.299681,NaN,0.384327,0.562223,0.400280,0.869896
min,0.000190,0.000000,-17.800000,0.000000,0.000000,0.026000,0.000000
25%,0.033000,0.004112,0.003785,0.000000,0.000000,0.485730,0.000000
50%,0.450000,0.031950,0.030000,0.000000,0.000000,0.675350,0.002095
75%,1.858750,0.150000,0.150000,0.006217,0.006000,0.816000,0.023000
max,50.000000,53.500000,inf,13.000000,20.900000,6.900000,48.000000

In [17]:
# Drops non-numeric columns like name automatically
df.corr(numeric_only=True)

,mass,mass_error_min,mass_error_max,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
mass,1.000000,0.355795,0.076234,0.248392,0.212409,0.184454,-0.005694
mass_error_min,0.355795,1.000000,0.022037,0.277648,0.203593,0.038371,-0.003247
mass_error_max,0.076234,0.022037,1.000000,0.019264,0.030532,0.002400,-0.001200
mass_sini_error_min,0.248392,0.277648,0.019264,1.000000,0.737325,0.000291,-0.007144
mass_sini_error_max,0.212409,0.203593,0.030532,0.737325,1.000000,-0.010665,-0.005292
radius,0.184454,0.038371,0.002400,0.000291,-0.010665,1.000000,0.062880
radius_error_min,-0.005694,-0.003247,-0.001200,-0.007144,-0.005292,0.062880,1.000000

In [18]:
df['planet_status'].value_counts()

planet_status
Confirmed    3062
Name: count, dtype: int64

In [19]:
# fix infinite values by replacing inf with NaN, then filling them with 0
df = df.replace([np.inf, -np.inf], np.nan)
df['mass_error_max'] = df['mass_error_max'].fillna(0)

In [20]:
# fix negative values by converting negative error values to 0
df['mass_error_max'] = df['mass_error_max'].clip(lower=0)

In [21]:
# drop planet_status because every row is 'Confirmed'
df = df.drop(columns=['planet_status'], errors='ignore')

In [22]:
# save final dataset
df.to_csv("Cleaned_Exoplanet_Data_Final.csv", index=False)

In [23]:
df.describe()

,mass,mass_error_min,mass_error_max,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
count,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000
mean,1.653834,0.298412,0.627826,0.072848,0.081591,0.699602,0.037602
std,2.866224,1.299681,15.475486,0.384327,0.562223,0.400280,0.869896
min,0.000190,0.000000,0.000000,0.000000,0.000000,0.026000,0.000000
25%,0.033000,0.004112,0.003590,0.000000,0.000000,0.485730,0.000000
50%,0.450000,0.031950,0.030000,0.000000,0.000000,0.675350,0.002095
75%,1.858750,0.150000,0.140000,0.006217,0.006000,0.816000,0.023000
max,50.000000,53.500000,850.000000,13.000000,20.900000,6.900000,48.000000